### ISSUE TITLE
Where/How do I configure the translation of local links to public URLS

### ISSUE THREAD

**Issue by DragonNZ** [silverstripe-archive/silverstripe-newsletter#138]
Hi,

When I put in a local link to a file (e.g. Uploads/files/file.png) or page on the site, it gets translated to a URL like this
http://mysite,com/var/www/clients/client5/web21/web/assets/Uploads/files/file.png (which is not browseable)
And I want it to be this link which is
https://mysite.com/assets/Uploads/files/file.png

Where do I do this in the configuration?

Thanks in advance
   John

**Comment by wilr** [comment]
@DragonNZ this isn't a config option - it looks like your template or something may be using $Path rather than $URL. Or your `SS_BASE_URL` is set to `var/www/` rather than `http://yoursite.com`. 

As far I I know there isn't anything in the core module which would manage this information. Are you attaching the files into TinyMCE?

**Comment by DragonNZ** [comment]
@wilr thank you for the reply. I'm using SS3 and as far as I can tell the SS_BASE_URL is set correctly via the directors alternate_base_url , $path is not used anywhere I can see and I am not attaching files into TinyMCE.

I just don't use SS enough to find my way around it easily and just can't seem to find any guidance in the documentation in terms of getting these settings right.

As this is the only issue I am having, I have added a line in the email php code to replace the unwanted path with a '/' and it's working a treat. So I am going to leave it there until I happen across the right way of doing it in the future.
